/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  Thomas
 * Created: 27.10.2024
 */

INSERT INTO BOOTS (TYPE, SIZE, QUANTITY, MATERIAL) VALUES ('CHELSEA', 10.5, 6, 'leather');
INSERT INTO BOOTS (TYPE, SIZE, QUANTITY, MATERIAL) VALUES ('GOGO', 6.5, 6, 'rubber');
INSERT INTO BOOTS (TYPE, SIZE, QUANTITY, MATERIAL) VALUES ('GOGO', 7.5, 16, 'rubber');
INSERT INTO BOOTS (TYPE, SIZE, QUANTITY, MATERIAL) VALUES ('CHUKKA', 8.0, 8, 'leather');
INSERT INTO BOOTS (TYPE, SIZE, QUANTITY, MATERIAL) VALUES ('CHUKKA', 7.0, 3, 'canvas');
INSERT INTO BOOTS (TYPE, SIZE, QUANTITY, MATERIAL) VALUES ('RACING', 9.5, 20, 'leather');
INSERT INTO BOOTS (TYPE, SIZE, QUANTITY, MATERIAL) VALUES ('UGG', 6.5, 4, 'suede');
INSERT INTO BOOTS (TYPE, SIZE, QUANTITY, MATERIAL) VALUES ('DRESS', 10.5, 4, 'leather');
INSERT INTO BOOTS (TYPE, SIZE, QUANTITY, MATERIAL) VALUES ('GALOSH', 7.5, 14, 'rubber');

--INSERT INTO BOOTS (ID, TYPE, SIZE, QUANTITY, MATERIAL) VALUES (-4, 'CHELSEA', 10.5, 6, 'leather');
--INSERT INTO BOOTS (ID, TYPE, SIZE, QUANTITY, MATERIAL) VALUES (-3, 'GOGO', 6.5, 6, 'rubber');
--INSERT INTO BOOTS (ID, TYPE, SIZE, QUANTITY, MATERIAL) VALUES (-2, 'GOGO', 7.5, 16, 'rubber');
--INSERT INTO BOOTS (ID, TYPE, SIZE, QUANTITY, MATERIAL) VALUES (-1, 'CHUKKA', 8.0, 8, 'leather');
